<?php
session_start();
$session_id = 1;
$cfg = parse_ini_file("../inc/config.ini"); // Загружаем наши дефолтные настройки
$dbhost = $cfg['host'];
$dbuser = $cfg['user'];
$dbpass = $cfg['password'];
$db = $cfg['database'];
$path = "../uploads/";

include('./Classes/PHPExcel.php'); // Подгружаем класс PHPExcel

date_default_timezone_set('Asia/Irkutsk');
setlocale(LC_ALL, 'ru_RU');

$SUCCESS = '<div class="alert alert-success"><a class="close" data-dismiss="alert" href="#">&times;</a>Файл успешно загружен! ПОЗДРАВЛЯЕМ! Вы сделали это!</div>';
$ERR_FATAL = '<div class="alert alert-error"><a class="close" data-dismiss="alert" href="#">&times;</a>Критическая ошибка! ТЫ ВСЕ СЛОМАЛ! Иди теперь, ремонтируй все!</div>';
$ERR_SIZE = '<div class="alert alert-error"><a class="close" data-dismiss="alert" href="#">&times;</a>Размер изображение превышает 10 МБ, нахуя такой большой файл? Мариновать?</div>';
$ERR_FILE = '<div class="alert alert-error"><a class="close" data-dismiss="alert" href="#">&times;</a>Неверный тип файла! Ты вообще смотрел какие типы файла поддерживаются?</div>';
$ERR_EMPTY = '<div class="alert alert-error"><a class="close" data-dismiss="alert" href="#">&times;</a>Выберите ваш херов файл&hellip;</div>';

$valid_formats = array("xls", "xlsx");
if (isset($_POST) && $_SERVER['REQUEST_METHOD'] == "POST") {
	if (isset($_FILES['comptek-template'])) {
		$name = $_FILES['comptek-template']['name'];
		$size = $_FILES['comptek-template']['size'];
		$tmp = $_FILES['comptek-template']['tmp_name'];
	}
	if (isset($_FILES['comptek-price'])) {
		$name = $_FILES['comptek-price']['name'];
		$size = $_FILES['comptek-price']['size'];
		$tmp = $_FILES['comptek-price']['tmp_name'];
	}
	if (strlen($name)) {
		list($txt, $ext) = explode(".", $name);
		$ext = strtolower($ext);
		if (in_array($ext, $valid_formats)) {
			if ($size<(10485760)) { // Размер файла максимально 10 МБайт
				$actual_file_name = time().$session_id.'.'.$ext;
				if (move_uploaded_file($tmp, $path.$actual_file_name)) {
					if (isset($_FILES['comptek-template'])) echo getDataFromTemplate($actual_file_name);
					if (isset($_FILES['comptek-price'])) echo getDataFromPrice($actual_file_name);
					unlink($path.$actual_file_name);
				} else { echo $ERR_FATAL; }
			 } else { echo $ERR_SIZE; }
		} else { echo $ERR_FILE; }
	} else { echo $ERR_EMPTY; }
}

function getDataFromPrice($fileName) {

	class MyReadFilter implements PHPExcel_Reader_IReadFilter
	{
		public function readCell($column, $row, $worksheetName = '') {
			$Retour = false;
			$column = PHPExcel_Cell::columnIndexFromString($column);
			if ($column <= 3) $Retour = true;
			else $Retour = false;
			return $Retour;
		}
	} 
	
	$inputFileType = PHPExcel_IOFactory::identify($GLOBALS['path'].$fileName);
	$objReader = PHPExcel_IOFactory::createReader($inputFileType);
	
	$objReader->setReadDataOnly(true);
	$objReader->setReadFilter( new MyReadFilter() );
	$objPHPExcel = $objReader->load($GLOBALS['path'].$fileName);
	$objWorksheet = $objPHPExcel->getSheet(0);

	$i = 1;
	echo '<p><span class="label label-warning">ВНИМАНИЕ!</span> Ознакомтесь со следующей таблицей и сравните с исходными данными, 10 первых строк должны соответствовать 10 первым позициям прайса, если это не так, сообщите разработчику!!! Также замечу что цены приведены без партнерской скидки.</p>';
	echo '<table class="table table-hover table-bordered">';
	echo '<tr><th style="text-align:center">PEC код</th><th style="text-align:center">Описание</th><th style="text-align:center">Цена</th>';
	
	$sqlPriceDataStart  = "-- PBX Configurator\n-- version 1.0.1\n--\n-- Generated by Arsen Bespalov\n\n";
	$sqlPriceDataStart .= "SET SQL_MODE=\"NO_AUTO_VALUE_ON_ZERO\";\n";
	$sqlPriceDataStart .= "SET time_zone = \"+00:00\";\n\n";
	$sqlPriceDataStart .= "/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;\n";
	$sqlPriceDataStart .= "/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;\n";
	$sqlPriceDataStart .= "/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;\n";
	$sqlPriceDataStart .= "/*!40101 SET NAMES utf8 */;\n\n";
	$sqlPriceDataStart .= "-- --------------------------------------------------------\n\n";
	$sqlPriceDataStart .= "--\n". "-- Dumping data for table `Price`\n". "--\n\n";
	$sqlPriceDataStart .= "LOCK TABLES `Price` WRITE;\n";
	$sqlPriceDataInsert = "REPLACE INTO `Price` (`PEC`, `Desc`, `Price`, `Vender`) VALUES\n";
	file_put_contents($GLOBALS['path'].'price.sql', $sqlPriceDataStart.$sqlPriceDataInsert);
	$sqlPriceData = '';
	
	foreach ($objWorksheet->getRowIterator() as $row) {
		
		$cellIterator = $row->getCellIterator();
		$cellIterator->setIterateOnlyExistingCells(false);
		
		$x = 1;
		
		if ($i >= 8) {
			if ($i <= 17) echo '<tr>';
			if ($i % 1500) {
				$sqlPriceData .= '(';
			} else {
				$sqlPriceData  = rtrim($sqlPriceData, ",\n");
				$sqlPriceData .= ";\n".$sqlPriceDataInsert.'(';
			}
		}
		
		foreach ($cellIterator as $cell) {
			if ($i >= 8) {
				if ($i <= 17) {
					if ($x == 3) 
						$fin = '$'.number_format(round($cell->getValue(), 2), 2, ',', ' ');
					else 
						$fin = $cell->getValue();
						
					if ($x == 1) $td_align = 'center';
					elseif ($x == 3) $td_align = 'right';
					else $td_align = 'left';
					
					echo '<td style="text-align:'.$td_align.'">'. $fin . '</td>';
				}
				// Составляем данные
				if ($x == 2) $sqlData = addslashes($cell->getValue());
				else $sqlData = $cell->getValue();
				if ($x != 3) $sqlPriceData .= "'".$sqlData."',";
				else $sqlPriceData .= "'".$sqlData."'";
			}
			$x++;
		}
		
		if ($i >= 8) {
			$sqlPriceData .= ",'Avaya'),\n";
			if ($i <= 17) echo '</tr>';
		}
		$i++;
	}
	echo '</table>';
	$sqlPriceData = rtrim($sqlPriceData, ",\n").";\n";
	$sqlPriceDataEnd = "UNLOCK TABLES;\n";
	file_put_contents($GLOBALS['path'].'price.sql', $sqlPriceData.$sqlPriceDataEnd, FILE_APPEND | LOCK_EX);
	$val =  $objWorksheet->getCell('B2')->getValue();
	$date1 = explode(" ", $val);
	$date2 = explode(".", $val);
	if (count($date1) == 1 && count($date2) == 1) {
		$val = date('d.m.Y', PHPExcel_Shared_Date::ExcelToPHP($val));
	}
	$priceTime = strtotime($val);
	$currTime = strtotime("now");
	if (($priceTime + (86400*30)) < $currTime ) $date_class = ' alert-error';
	else $date_class = ' alert-success';
	echo '<div class="alert'.$date_class.'"><strong>Дата прайса:</strong> '.strftime('%e %B %Y года', $priceTime).'</div>';
	echo '<div class="well" style="max-width: 400px; margin: 0 auto 10px;">';
	echo '<a class="btn btn-primary btn-block" href="#" id="import-price">Все Верно! Загрузить прайс!</a>';
	echo '<a class="btn btn-inverse btn-block" href="uploads/price.sql">Скачать SQL-файл прайса</a>';
	echo '</div>';
	
}

function getDataFromTemplate($fileName) {

	class MyReadFilter implements PHPExcel_Reader_IReadFilter
	{
		public function readCell($column, $row, $worksheetName = '') {
			$Retour = false;
			$column = PHPExcel_Cell::columnIndexFromString($column);
			if ($row >= 17 && $column <= 3 && $column != 2) $Retour = true;
			else $Retour = false;
			return $Retour;
		}
	}
	
	$inputFileType = PHPExcel_IOFactory::identify($GLOBALS['path'].$fileName);
	$objReader = PHPExcel_IOFactory::createReader($inputFileType);
	
	$objReader->setReadDataOnly(true);
	$objReader->setReadFilter( new MyReadFilter() );
	$objPHPExcel = $objReader->load($GLOBALS['path'].$fileName);
	$objWorksheet = $objPHPExcel->getSheet(0);
	
	$i = 1;
	echo '<p><span class="label label-warning">ВНИМАНИЕ!</span> Ознакомтесь со следующей таблицей, соответствуют ли записи таблицы логически верным данным, если это не так, сообщите разработчику!!!</p>';
	echo '<table class="table table-hover table-bordered">';
	echo '<tr><th style="text-align:center">PEC код</th><th style="text-align:center">Описание на русском</th>';
	
	$sqlPriceDataStart  = "-- PBX Configurator\n-- version 1.0.1\n--\n-- Generated by Arsen Bespalov\n\n";
	$sqlPriceDataStart .= "SET SQL_MODE=\"NO_AUTO_VALUE_ON_ZERO\";\n";
	$sqlPriceDataStart .= "SET time_zone = \"+00:00\";\n\n";
	$sqlPriceDataStart .= "/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;\n";
	$sqlPriceDataStart .= "/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;\n";
	$sqlPriceDataStart .= "/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;\n";
	$sqlPriceDataStart .= "/*!40101 SET NAMES utf8 */;\n\n";
	$sqlPriceDataStart .= "-- --------------------------------------------------------\n\n";
	$sqlPriceDataStart .= "--\n". "-- Dumping data for table `Translate`\n". "--\n\n";
	$sqlPriceDataStart .= "LOCK TABLES `Translate` WRITE;\n";
	$sqlPriceDataInsert = "REPLACE INTO `Translate` (`PEC`, `Text`) VALUES\n";
	file_put_contents($GLOBALS['path'].'template.sql', $sqlPriceDataStart.$sqlPriceDataInsert);
	$sqlPriceData = '';
	
	foreach ($objWorksheet->getRowIterator() as $row) {
		
		$cellIterator = $row->getCellIterator();
		$cellIterator->setIterateOnlyExistingCells(false);
		
		$x = 1;
		
		if ($i >= 17) {
			if ($i <= 22) echo '<tr>';
			if ($i % 1500) {
				$sqlPriceData .= '(';
			} else {
				$sqlPriceData  = rtrim($sqlPriceData, ",\n");
				$sqlPriceData .= ";\n".$sqlPriceDataInsert.'(';
			}
		}
		
		foreach ($cellIterator as $cell) {
			if ($i >= 17 && $x != 2 && $objWorksheet->getCell('A'.$i)->getValue() != '') {
				if ($i <= 22) {
					$fin = $cell->getValue();
						
					if ($x == 1) $td_align = 'center';
					else $td_align = 'left';
					
					echo '<td style="text-align:'.$td_align.'">'. $fin . '</td>';
				}
				// Составляем данные
				if ($x == 3) $sqlData = addslashes($cell->getValue());
				else $sqlData = $cell->getValue();
				if ($x != 3) $sqlPriceData .= "'".$sqlData."',";
				else $sqlPriceData .= "'".$sqlData."'";
			}
			$x++;
		}
		
		if ($i >= 17) {
			$sqlPriceData .= '),'."\n";
			if ($i <= 22) echo '</tr>';
		}
		$i++;
	}
	echo '</table>';
	$sqlPriceData = str_replace("(),\n", "", $sqlPriceData);
	$sqlPriceData = str_replace("('Цены DDP Москва включают все налоги. Срок поставки зависит от комплектации.',''),\n", "", $sqlPriceData);
	$sqlPriceData = rtrim($sqlPriceData, ",\n").";\n";
	$sqlPriceDataEnd = "UNLOCK TABLES;\n";
	file_put_contents($GLOBALS['path'].'template.sql', $sqlPriceData.$sqlPriceDataEnd, FILE_APPEND | LOCK_EX);
	echo '<div class="well" style="max-width: 400px; margin: 0 auto 10px;">';
	echo '<a class="btn btn-primary btn-block" href="#" id="import-template">Все Верно! Загрузить шаблон!</a>';
	echo '<a class="btn btn-inverse btn-block" href="uploads/template.sql">Скачать SQL-файл шаблона</a>';
	echo '</div>';
}